#!name=Duolingo Max 解锁
#!desc=解锁 Duolingo Max 会员
#!author=Takagivegeta

[MITM]
hostname = %APPEND% ios-api-*.duolingo.com, ios-api-*.duolingo.cn, api*.duolingo.com, api*.duolingo.cn

[Script]
duolingo_max = type=http-response,pattern=^https?:\/\/(ios-api-[a-z0-9-]+|api\d+)\.duolingo\.c(n|om)\/2023-05-23\/batch,script-path=https://raw.githubusercontent.com/TAKAGIVEGETA/MyScripts/main/lingoDuo/lingoDuo-xaM.js,requires-body=1,max-size=0,timeout=120
